[core]
plugins = \
  alpha \
  animate \
  autostart \
  command \
  core \
  decoration \
  expo \
  grid \
  move \
  place \
  resize \
  switcher \
  vswitch \
  window-rules \
  wm-actions \
  wobbly \
  wproto \
  foreign-toplevel \
  blur

[blur]
# Método de blur: 'kawase' es el más balanceado entre calidad/rendimiento
method = kawase

# INTENSIDAD: Ajusta estos dos valores
# El radio define qué tan lejos llega el difuminado
radius = 7
# Las iteraciones definen cuántas veces se aplica el filtro (más = más suave)
iterations = 5

# Opcional: blur en el modo 'expo' o 'switcher'
blur_by_default = all

[input]
xkb_layout=us

[output:eDP-1]
mode=1920x1080@60
position=299,1437
transform=normal

[output:HDMI-A-1]
mode=2560x1440@60
position=0,0
transform=normal
