[preferred]
# Por defecto delegamos todo a GTK (ej: AppChooser, Print)
default=gtk;

# Para la configuración del sistema (Temas/Colores), usamos nuestro portal nativo
org.freedesktop.impl.portal.Settings=horizon;

# Para los dialogos de archivos usamos el portal nativo
org.freedesktop.impl.portal.FileChooser=horizon;
