[preferred]
# Por defecto delegamos todo a GTK (ej: FileChooser, AppChooser, Print)
default=gtk;

# Pero para la configuración del sistema (Temas/Colores), usamos nuestro portal nativo
org.freedesktop.impl.portal.Settings=horizon;
