add_executable(preferences
    src/main.cpp
    src/PreferencesWindow.cpp
    src/PreferencesToolbar.cpp
    src/ContentView.cpp
    src/ViewPanel.cpp
    src/ConfigManager.cpp
    src/ImagesView.cpp
    src/views/DesktopView/DesktopView.cpp
    src/views/DesktopView/WallpaperView.cpp
    src/views/DesktopView/DockView.cpp
    src/views/AppearanceView/AppearanceView.cpp
    src/views/ScreensaverView/ScreensaverView.cpp
    src/views/NotificationsView/NotificationsView.cpp
    src/views/DisplayView/DisplayView.cpp
    src/views/DisplayView/DisplayDevices.cpp
    src/views/DisplayView/LabwcAdapter.cpp
    src/views/DisplayView/KwinAdapter.cpp
    src/views/DisplayView/WayfireAdapter.cpp
    src/views/SoundView/SoundView.cpp
    src/views/MouseView/MouseView.cpp
    src/views/KeyboardView/KeyboardView.cpp
    src/views/KeyboardView/KeyboardHardwareView.cpp
    src/views/PrintersView/PrintersView.cpp
    src/views/PowerView/PowerView.cpp
    src/views/WifiView/WifiView.cpp
    src/views/WifiView/WifiConfigView.cpp
    src/views/BluetoothView/BluetoothView.cpp
    src/views/NetworkView/NetworkView.cpp
    src/views/UsersView/UsersView.cpp
    src/views/DateTimeView/DateTimeView.cpp
    src/views/RegionView/RegionView.cpp
    src/views/DetailsView/DetailsView.cpp
    src/views/ApplicationsView/ApplicationsView.cpp
    src/views/ApplicationsView/MimeTypesView.cpp
    src/views/ApplicationsView/InputDialog.cpp
    src/views/ApplicationsView/AppPickerDialog.cpp
    src/views/ApplicationsView/DefaultAppsView.cpp
    src/views/ApplicationsView/StartupAppsView.cpp
    src/views/ApplicationsView/StartupEditDialog.cpp
    src/utils/DesktopManager.cpp
    src/utils/XkbParser.cpp
    src/utils/WayfireConfigWriter.cpp
    src/views/KeyboardView/KeyboardLanguageView.cpp
    src/views/ApplicationsView/LayoutPickerDialog.cpp
)

target_link_libraries(preferences
    PRIVATE
        horizon
)

target_include_directories(preferences
    PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}/include
)
