content = """
include("${CMAKE_BINARY_DIR}/CPackConfig.cmake")
set(CPACK_COMPONENTS_ALL "${LIB_COMPONENTS}")
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE OFF)
set(CPACK_COMPONENTS_GROUPING "IGNORE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
"""
print(content)
