#pragma once

#include <string>

namespace horizon::lens
{
    /**
     * @enum ThumbnailSize
     * @brief Available thumbnail sizes following the XDG Thumbnail Specification.
     */
    enum class ThumbnailSize
    {
        Normal,  ///< 128x128 px — for list views and small icons
        Large,   ///< 256x256 px — for grid view (default in arkfm)
        XLarge   ///< 512x512 px — for cover flow and previews
    };

    /**
     * @class ThumbnailCache
     * @brief Client-side API to query and request thumbnails generated by horizon-lens.
     *
     * Thumbnails are stored persistently in ~/.cache/horizon/thumbnails/ following
     * a subset of the XDG Thumbnail Specification. Any application can use this
     * class without depending on horizon-lens being active — it simply reads from disk.
     *
     * If horizon-lens is running, it will asynchronously generate thumbnails in the
     * background. Apps can call request_thumbnail() to hint that a specific file
     * should be prioritized.
     */
    class ThumbnailCache
    {
    public:
        /**
         * @brief Returns the path to the cached thumbnail for a given file, if valid.
         *
         * A thumbnail is considered valid when:
         *  - The PNG file exists in the cache directory.
         *  - Its embedded Thumb::MTime metadata matches the current mtime of the source file.
         *
         * @param file_path  Absolute path to the original file (image or PDF).
         * @param size       Desired thumbnail size. Default is Large (256x256).
         * @return Absolute path to the cached PNG thumbnail, or an empty string if
         *         no valid thumbnail exists yet.
         */
        static std::string get_thumbnail(const std::string& file_path,
                                         ThumbnailSize size = ThumbnailSize::Large);

        /**
         * @brief Requests horizon-lens to generate a thumbnail with high priority.
         *
         * Writes a small request file into ~/.cache/horizon/thumbnails/queue/ so the
         * daemon picks it up via inotify and jumps it to the front of the work queue.
         * This call is non-blocking and safe to call from the UI thread.
         *
         * @param file_path  Absolute path to the file that needs a thumbnail.
         * @param size       Desired thumbnail size.
         */
        static void request_thumbnail(const std::string& file_path,
                                      ThumbnailSize size = ThumbnailSize::Large);

        /**
         * @brief Returns the expected path of a thumbnail without checking if it exists.
         *
         * Useful for pre-registering a watcher (e.g. FileWatcher) so the app can
         * be notified when horizon-lens generates the thumbnail.
         *
         * @param file_path  Absolute path to the original file.
         * @param size       Desired thumbnail size.
         * @return Expected absolute path of the thumbnail PNG.
         */
        static std::string thumbnail_path_for(const std::string& file_path,
                                              ThumbnailSize size = ThumbnailSize::Large);

        /**
         * @brief Returns the root directory for the given thumbnail size.
         * e.g. ~/.cache/horizon/thumbnails/large/
         */
        static std::string cache_dir(ThumbnailSize size = ThumbnailSize::Large);

        /**
         * @brief Returns true if the file extension is supported for thumbnailing.
         */
        static bool is_supported(const std::string& file_path);

        /**
         * @brief Removes a stale thumbnail from the cache (e.g. after a file is deleted).
         */
        static void invalidate(const std::string& file_path,
                               ThumbnailSize size = ThumbnailSize::Large);

    private:
        /**
         * @brief Computes the MD5 hex digest of the file:// URI for the given path.
         * This follows the XDG Thumbnail Specification naming convention.
         */
        static std::string compute_uri_md5(const std::string& file_path);
    };

} // namespace horizon::lens
